source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
inhibit_all_warnings!
target 'TmpProduct' do
  pod 'AFNetworking' , '~> 3.1.0'
  pod 'SDCycleScrollView', '~> 1.74'
#  pod 'SDWebImage'
	pod 'MJExtension', '~> 3.0.13'
	pod 'MLTransition', '~> 2.1.3'
	pod 'MJRefresh', '~> 3.1.12'
  pod 'GBDeviceInfo'
#  pod 'MBProgressHUD', '~> 1.0.0'
#  pod 'YJProgressHUD', '~> 1.0.4'
	pod 'MBProgressHUD+JDragon', '~> 0.0.3'
  pod 'FLEX', '~> 2.4.0'
  pod 'JPFPSStatus', '~> 0.1.1'
	pod 'Masonry'
	pod 'TZImagePickerController', '~> 1.9.3'
  pod 'FDFullscreenPopGesture'
	#pod 'TXJAllTools'
  pod 'JHChainableAnimations', '~> 3.0.1'
	pod 'IQKeyboardManager'
	pod 'YYText'
  #pod 'AXAnimationChain', '~> 0.4.1'
  pod 'LLSegmentBar'
	pod 'YYModel'
  pod 'YYCache'
  pod 'PGDatePicker'
  pod 'NYXImagesKit'
  pod 'ReactiveObjC', '~> 3.1.0'
  pod 'JPush'#极光推送
end
